name: Prerelease
on:
  workflow_call:
  workflow_dispatch:

jobs:
  prerelease:
    name: Prerelease
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Set version
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          npm version 0.0.0
          npm version $(npm pkg get version | sed 's/"//g')-$(date +'%Y%m%dT%H%M%S')
          git push --tags

      - name: Build
        run: bun run build

      - name: Zip
        run: cd dist/build && zip -r ../extension.zip *

      - name: Get NPM version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/extension.zip
          prerelease: true
          tag_name: 'v${{ steps.package-version.outputs.current-version }}'
